nodeLinker: "node-modules"
# packageExtensions:
#   "@comunica/actor-abstract-parse@*":
#     dependencies:
#       "@types/node": ^18
#       "@types/readable-stream": ^4
#   "@comunica/types@*":
#     dependencies:
#       "@types/node": ^18
#   "@solid/community-server@*":
#     dependencies:
#       "@types/koa": ^2
#       rdf-js: ^2
#   asynciterator@*:
#     dependencies:
#       "@types/node": ^18
#   rdf-parse@*:
#     dependencies:
#       "@types/node": ^18
#       "@types/readable-stream": ^4
#       rdf-js: ^2
#   undici-types@*:
#     dependencies:
#       "@types/node": ^18
#   winston-transport@*:
#     dependencies:
#       "@types/node": ^18
#   winston@*:
#     dependencies:
#       "@types/node": ^18
