version: '3.4'

services:
  user-managed-access:
    image: css-uma-main
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 4000:4000