version: '3.4'

services:
  pacsoi-poc-1:
    image: pacsoi-poc1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 4000:4000
      - 4444:4444
      - 5123:5123
      - 8201:8201
      - 8202:8202
      - 8203:8203
