### TODO: doc
POST http://localhost:4444/issue
Content-Type: application/json

{
  "email": "government@belgium.be",
  "password": "abc123",
  "css": "http://localhost:3000/",
  "webId": "http://localhost:3000/gov-data-registry/profile/card#me",
  "contentType": "application/n-quads",
  "data": "<http://www/example.com/data/component-c01> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www/example.com/ont/Component> ."
}
