### TODO: doc
POST http://localhost:4444/setup
Content-Type: application/json

{
  "email": "government@belgium.be",
  "password": "abc123",
  "css": "http://localhost:3000/",
  "webId": "http://localhost:3000/gov-data-registry/profile/card#me"
}
