
name: Push

on: [ push ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.x # Maintenance
          - 20.x # Active
          - 21.x # Current

    steps:

      - name: Enable Node.js Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Yarn install
        run: yarn install
